# Generated by Django 4.2 on 2023-04-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nama_lengkap',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nomor_telepon',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='usia',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
