# Generated by Django 4.2 on 2023-04-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_nama_lengkap_user_nomor_telepon_user_usia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usia',
            field=models.IntegerField(default=0),
        ),
    ]
