# Generated by Django 4.2 on 2023-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=150)),
                ('jenis', models.CharField(choices=[('Obat', 'Obat'), ('Suplemen', 'Suplemen')], max_length=20)),
                ('deskripsi', models.TextField()),
                ('khasiat', models.CharField(max_length=255)),
                ('dosis', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('satuan', models.CharField(max_length=100)),
            ],
        ),
    ]
