# Generated by Django 4.2 on 2023-04-26 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dokter', '0002_alter_dokter_lokasi_praktek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Janji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('keluhan', models.TextField()),
                ('dokter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dokter.dokter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
