# Generated by Django 4.2 on 2023-04-27 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokter', '0002_alter_dokter_lokasi_praktek'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('janji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janji',
            name='dokter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokter.dokter'),
        ),
        migrations.AlterField(
            model_name='janji',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
