# Generated by Django 4.2 on 2023-04-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('gejala', models.TextField()),
                ('pencegahan', models.TextField()),
                ('pengobatan', models.TextField()),
            ],
        ),
    ]
