# Generated by Django 4.2 on 2023-04-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyakit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyakit',
            name='penyebab',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
