# Generated by Django 4.2 on 2023-04-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyakit', '0002_penyakit_penyebab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penyakit',
            options={'ordering': ('nama',)},
        ),
        migrations.AlterField(
            model_name='penyakit',
            name='penyebab',
            field=models.TextField(default=''),
        ),
    ]
