# Generated by Django 4.2 on 2023-04-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('daerah', models.CharField(choices=[('Jakarta Utara', 'Jakarta Utara'), ('Jakarta Selatan', 'Jakarta Selatan'), ('Jakarta Pusat', 'Jakarta Pusat'), ('Jakarta Barat', 'Jakarta Barat'), ('Jakarta Timur', 'Jakarta Timur')], max_length=100)),
                ('no_telepon', models.CharField(max_length=25)),
                ('deskripsi', models.TextField()),
                ('fasilitas', models.TextField()),
            ],
        ),
    ]
