# Generated by Django 4.2 on 2023-04-27 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_remove_order_nama_item_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='nama_lengkap',
        ),
        migrations.AddField(
            model_name='order',
            name='quantities',
            field=models.CharField(default='[]', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
