# Generated by Django 4.2 on 2023-04-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0001_initial'),
        ('dokter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='lokasi_praktek',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rumah_sakit.rs'),
        ),
    ]
